### ISSUE TITLE
Key error: 'mqreader'

### ISSUE THREAD

**Issue by piotrsan** [siheming/mspypeline#34]
Hello,

thanks for making this package available!

I am trying to run this on a Mac M1max.

I have created a virtual env using the following:

```
conda create --name mspypeline
conda activate mspypeline
conda config --env --set subdir osx-64
conda install -c conda-forge -c siheming mspypeline 
```

When I try to run the analysis with the GUI I get the following error:
```
raceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mspypeline/lib/python3.8/site-packages/mspypeline/core/MSPPlots/BasePlotter.py", line 143, in __init__
    self.required_reader_data = reader_data[required_reader]
KeyError: 'mqreader'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mspypeline/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mspypeline/lib/python3.8/site-packages/mspypeline/core/MSPypeline.py", line 169, in <lambda>
    command=lambda: self.report_button())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mspypeline/lib/python3.8/site-packages/mspypeline/core/MSPypeline.py", line 388, in report_button
    mspplots = self.selected_reader.plotter.from_MSPInitializer(self.mspinit)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mspypeline/lib/python3.8/site-packages/mspypeline/core/MSPPlots/MaxQuantPlotter.py", line 76, in from_MSPInitializer
    return super().from_MSPInitializer(mspinit_instance, **default_kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mspypeline/lib/python3.8/site-packages/mspypeline/core/MSPPlots/BasePlotter.py", line 209, in from_MSPInitializer
    return cls(**default_kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mspypeline/lib/python3.8/site-packages/mspypeline/core/MSPPlots/MaxQuantPlotter.py", line 55, in __init__
    super().__init__(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mspypeline/lib/python3.8/site-packages/mspypeline/core/MSPPlots/BasePlotter.py", line 143, in __init__
    self.required_reader_data = reader_data[required_reader]
KeyError: 'mqreader'
```

Would you be able to help me sort out this error?

Thanks,

Piero

**Comment by siheming** [comment]
Hi Piero,

can you share the yml file, that was created to analyze the experiment? I am not sure how this error could come from looking at the trackeback. It seems like the data was stored under another key, but this should not really happen.

**Comment by piotrsan** [comment]
Thanks for looking into this.
[config.yml.zip](https://github.com/siheming/mspypeline/files/9144119/config.yml.zip)

Here is the yml file.

**Comment by siheming** [comment]
The file seems to be fine, so I am guessing that the csv file by max quant is not read corretly. The program was tested with max quant 1.5+ but there might be older (or newer) versions for which this does not work. It might also be that you are using a different delimiter, currently tabs are expected. If you can, you could also share the first few lines of your csv file, so I could take a look.

**Comment by siheming** [comment]
If you still run into issues reopen the issue, but I will close it for now

**Comment by Benfeitas** [comment]
Hi I'm facing the same issue, for public data. I'm trying to examine the `SerumVsPlasma` files in [here](https://www.ebi.ac.uk/pride/archive/projects/PXD011749). My yaml file is very similar to the one above, with the difference that I have no GO_terms specified. How to overcome this issue?

**Comment by siheming** [comment]
Hi @Benfeitas , I would guess the same issue. I dont have a lot of free time on my hand unfourtunatly so I did not manage to take a closer look at the file you linked. Are you familiar with python? If yes you could try to look into the file reader of maxquant. https://github.com/siheming/mspypeline/blob/master/mspypeline/file_reader/MQReader.py . Otherwise you could compare it to the csv in the public dataset https://github.com/siheming/mspypeline_public_dataset/tree/122966b0e29ce53698371d4c1d65dff8c89f2fbe/txt . Maybe you could also tell me how your file structure currently looks like. My tool expects there to be something like this
```
some_experiment
|- txt
|-- proteinGroups.txt
|-- etc...
```
So it might be that you have to restructure the files similar to the output that max quant generates
